# Generated by Django 3.1.4 on 2020-12-07 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsearch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='hospital_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(choices=[(0, 'Hospitals'), (1, 'Clinics'), (2, 'Blood Banks'), (3, 'Labs')], default=0, max_length=250),
        ),
    ]
