# Generated by Django 2.2.17 on 2021-05-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsearch', '0002_auto_20201207_1147'),
        ('newsearch', '0007_hospital_address'),
    ]

    operations = [
    ]
