# Generated by Django 2.2.17 on 2021-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsearch', '0008_merge_20210528_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
