# Generated by Django 3.1.4 on 2020-12-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='reward',
            field=models.IntegerField(default=0),
        ),
    ]
