# Generated by Django 2.2.17 on 2021-05-28 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bldon', '0002_donor_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='last_donate',
            field=models.DateField(default=datetime.date(2021, 2, 17)),
        ),
    ]
